version: "3.4"

services:
  ai-ecom-backend:
    image: ai-ecom-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - $PORT:$PORT
